# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: daniel-castillo <daniel-castillo@studen    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2026/03/28 15:38:43 by daniel-cast       #+#    #+#              #
#    Updated: 2026/03/28 15:38:45 by daniel-cast      ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME= ScalarConverter
SRCS= main.cpp ScalarConverter.cpp
INC= ScalarConverter.hpp
